@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY
@REM THIS IS FOR TESTING ONLY

make
COPY .\build\rblxcpp.exe ..\testing
TIMEOUT 10
DEL .\build\rblxcpp.exe